## Lấy dữ liệu tại bảng BR

In [1]:
import pandas as pd
import numpy as np

- Get data path

In [2]:
import os.path as path
data_path =  path.abspath(path.join('' ,"../../data/historical_data"))
data_path = data_path + '\\BR.pickle.gz'
data_path

'D:\\Funix_FPT\\DataScience\\Final_Project\\horse_race_project\\data\\historical_data\\BR.pickle.gz'

In [3]:
BR_df = pd.read_pickle(data_path)
BR_df

,filename,line_no,head$RecordSpec,head$DataKubun,head$MakeDate$Year,head$MakeDate$Month,head$MakeDate$Day,BreederCode,BreederName_Co,BreederName,...,HonRuikei$2$SetYear,HonRuikei$2$HonSyokinTotal,HonRuikei$2$FukaSyokin,HonRuikei$2$ChakuKaisu$1,HonRuikei$2$ChakuKaisu$2,HonRuikei$2$ChakuKaisu$3,HonRuikei$2$ChakuKaisu$4,HonRuikei$2$ChakuKaisu$5,HonRuikei$2$ChakuKaisu$6,crlf
0,BRFW2018090320180903133011.json,1,BR,2,2018,9,3,14,辻 牧場,辻 牧場,...,0,122022650,940276,637,626,587,588,565,4599,\r\n
1,BRFW2018090320180903133011.json,2,BR,2,2018,9,3,49,王蔵牧場,王蔵牧場,...,0,9212300,37914,60,57,64,73,71,647,\r\n
2,BRFW2018090320180903133011.json,3,BR,2,2018,9,3,316,細川農場,細川農場,...,0,18557350,126006,106,100,113,100,120,821,\r\n
3,BRFW2018090320180903133011.json,4,BR,2,2018,9,3,318,森田 芳男,森田 芳男,...,0,3444750,8830,26,30,31,28,38,267,\r\n
4,BRFW2018090320180903133011.json,5,BR,2,2018,9,3,319,ヒカル牧場,ヒカル牧場,...,0,15851700,164462,82,87,79,76,84,621,\r\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17037,BRFW2018053120180531190115.json,2,BR,1,2018,5,31,110731,Desharon Bloodstock Stableboard Bloodstock ...,Desharon Bloodstock Stableboard Bloodstock ...,...,0,0,0,0,0,0,0,0,0,\r\n
17038,BRFW2018053120180531190115.json,3,BR,1,2018,5,31,130731,Frank Hutchinson ...,Frank Hutchinson ...,...,0,0,0,0,0,0,0,0,0,\r\n
17039,BRFW2018053120180531190115.json,4,BR,1,2018,5,31,300731,Carlos Rafael ...,Carlos Rafael ...,...,0,0,0,0,0,0,0,0,0,\r\n
17040,BRFW2018053120180531190115.json,5,BR,1,2018,5,31,370731,Deborah Shaffer ...,Deborah Shaffer ...,...,0,0,0,0,0,0,0,0,0,\r\n
17041,BRFW2018053120180531190115.json,6,BR,1,2018,5,31,380731,McMahon of Saratoga Thoroughbreds LLC ...,McMahon of Saratoga Thoroughbreds LLC ...,...,0,0,0,0,0,0,0,0,0,\r\n

In [2]:
BR_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17042 entries, 0 to 17041
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   filename                    17042 non-null  object
 1   line_no                     17042 non-null  int64
 2   head$RecordSpec             17042 non-null  object
 3   head$DataKubun              17042 non-null  int64
 4   head$MakeDate$Year          17042 non-null  int64
 5   head$MakeDate$Month         17042 non-null  int64
 6   head$MakeDate$Day           17042 non-null  int64
 7   BreederCode                 17042 non-null  int64
 8   BreederName_Co              17042 non-null  object
 9   BreederName                 17042 non-null  object
 10  BreederNameKana             17042 non-null  object
 11  BreederNameEng              17042 non-null  object
 12  Address                     17042 non-null  object
 13  HonRuikei$1$SetYear         17042 non-null  int64
 14  HonRuikei$1$HonSyokinTotal  17042 non-null  int64
 15  HonRuikei$1$FukaSyokin      17042 non-null  int64
 16  HonRuikei$1$ChakuKaisu$1    17042 non-null  int64
 17  HonRuikei$1$ChakuKaisu$2    17042 non-null  int64
 18  HonRuikei$1$ChakuKaisu$3    17042 non-null  int64
 19  HonRuikei$1$ChakuKaisu$4    17042 non-null  int64
 20  HonRuikei$1$ChakuKaisu$5    17042 non-null  int64
 21  HonRuikei$1$ChakuKaisu$6    17042 non-null  int64
 22  HonRuikei$2$SetYear         17042 non-null  int64
 23  HonRuikei$2$HonSyokinTotal  17042 non-null  int64
 24  HonRuikei$2$FukaSyokin      17042 non-null  int64
 25  HonRuikei$2$ChakuKaisu$1    17042 non-null  int64
 26  HonRuikei$2$ChakuKaisu$2    17042 non-null  int64
 27  HonRuikei$2$ChakuKaisu$3    17042 non-null  int64
 28  HonRuikei$2$ChakuKaisu$4    17042 non-null  int64
 29  HonRuikei$2$ChakuKaisu$5    17042 non-null  int64
 30  HonRuikei$2$ChakuKaisu$6    17042 non-null  int64
 31  crlf                        17042 non-null  object
dtypes: int64(24), object(8)
memory usage: 4.2+ MB

In [2]:
for c in BR_df.columns:
    print(c)

filename
line_no
head$RecordSpec
head$DataKubun
head$MakeDate$Year
head$MakeDate$Month
head$MakeDate$Day
BreederCode
BreederName_Co
BreederName
BreederNameKana
BreederNameEng
Address
HonRuikei$1$SetYear
HonRuikei$1$HonSyokinTotal
HonRuikei$1$FukaSyokin
HonRuikei$1$ChakuKaisu$1
HonRuikei$1$ChakuKaisu$2
HonRuikei$1$ChakuKaisu$3
HonRuikei$1$ChakuKaisu$4
HonRuikei$1$ChakuKaisu$5
HonRuikei$1$ChakuKaisu$6
HonRuikei$2$SetYear
HonRuikei$2$HonSyokinTotal
HonRuikei$2$FukaSyokin
HonRuikei$2$ChakuKaisu$1
HonRuikei$2$ChakuKaisu$2
HonRuikei$2$ChakuKaisu$3
HonRuikei$2$ChakuKaisu$4
HonRuikei$2$ChakuKaisu$5
HonRuikei$2$ChakuKaisu$6
crlf

In [3]:
BR_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17042 entries, 0 to 17041
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   filename                    17042 non-null  object
 1   line_no                     17042 non-null  int64
 2   head$RecordSpec             17042 non-null  object
 3   head$DataKubun              17042 non-null  int64
 4   head$MakeDate$Year          17042 non-null  int64
 5   head$MakeDate$Month         17042 non-null  int64
 6   head$MakeDate$Day           17042 non-null  int64
 7   BreederCode                 17042 non-null  int64
 8   BreederName_Co              17042 non-null  object
 9   BreederName                 17042 non-null  object
 10  BreederNameKana             17042 non-null  object
 11  BreederNameEng              17042 non-null  object
 12  Address                     17042 non-null  object
 13  HonRuikei$1$SetYear         17042 non-null  int64
 14  HonRuikei$1$HonSyokinTotal  17042 non-null  int64
 15  HonRuikei$1$FukaSyokin      17042 non-null  int64
 16  HonRuikei$1$ChakuKaisu$1    17042 non-null  int64
 17  HonRuikei$1$ChakuKaisu$2    17042 non-null  int64
 18  HonRuikei$1$ChakuKaisu$3    17042 non-null  int64
 19  HonRuikei$1$ChakuKaisu$4    17042 non-null  int64
 20  HonRuikei$1$ChakuKaisu$5    17042 non-null  int64
 21  HonRuikei$1$ChakuKaisu$6    17042 non-null  int64
 22  HonRuikei$2$SetYear         17042 non-null  int64
 23  HonRuikei$2$HonSyokinTotal  17042 non-null  int64
 24  HonRuikei$2$FukaSyokin      17042 non-null  int64
 25  HonRuikei$2$ChakuKaisu$1    17042 non-null  int64
 26  HonRuikei$2$ChakuKaisu$2    17042 non-null  int64
 27  HonRuikei$2$ChakuKaisu$3    17042 non-null  int64
 28  HonRuikei$2$ChakuKaisu$4    17042 non-null  int64
 29  HonRuikei$2$ChakuKaisu$5    17042 non-null  int64
 30  HonRuikei$2$ChakuKaisu$6    17042 non-null  int64
 31  crlf                        17042 non-null  object
dtypes: int64(24), object(8)
memory usage: 4.2+ MB