## Merge các bảng tạo dữ liệu để dự đoán cho cuộc đua mới

In [137]:
import pandas as pd
import numpy as np
from collections import Counter
import warnings
warnings.filterwarnings("ignore")

- Get data path

In [ ]:
import os.path as path
folder_path =  path.abspath(path.join('' ,"../../data/new_race_data"))
folder_path

### 1. Load data

- RA table

In [ ]:
RA_df = pd.read_pickle(folder_path+'\\RA.pickle.gz')
RA_df

In [ ]:
# Convert id$JyoCD
RA_df['id$JyoCD'] = RA_df['id$JyoCD'].astype('int64')

- Tạo dữ liệu năm

In [ ]:
RA_df['Year'] = RA_df['id$Year']

- Tạo dữ liệu tháng

In [ ]:
RA_df['Month'] = RA_df['id$MonthDay'].apply(lambda x: int(x/100))
RA_df[['Month', 'id$MonthDay']][RA_df['Month']==12]

In [ ]:
# Tổng hợp giải thưởng trước trận đấu
syokinAfter = [ 'Honsyokin$1',                
               'Honsyokin$2',               
            'Honsyokin$3',                
            'Honsyokin$4',
            'Honsyokin$5',
            'Fukasyokin$1',
            'Fukasyokin$2',
            'Fukasyokin$3'
         ]
syokinBefore = [ 'HonsyokinBefore$1',                
                 'HonsyokinBefore$2',               
                'HonsyokinBefore$3',                
                'HonsyokinBefore$4',
                'HonsyokinBefore$5',
                'FukasyokinBefore$1',
                'FukasyokinBefore$2',
                'FukasyokinBefore$3'
               ]

for after, before in zip(syokinAfter, syokinBefore):
    #print(after, before)
    RA_df.loc[RA_df[before]!=0, after] = RA_df[before]

# Tạo cột mới
RA_df['Honsyokin'] = RA_df['Honsyokin$1'] + RA_df['Honsyokin$2'] + RA_df['Honsyokin$3'] + RA_df['Honsyokin$4'] + RA_df['Honsyokin$5']
RA_df['Fukasyokin'] = RA_df['Fukasyokin$1'] + RA_df['Fukasyokin$2'] + RA_df['Fukasyokin$3']

In [ ]:
RA_selected_columns =  ['id$Year',
                        'id$MonthDay',
                        'id$JyoCD',
                        'id$Kaiji',
                        'id$Nichiji',
                        'id$RaceNum',
                        'Year',
                        'Month',
                        'RaceInfo$TokuNum',
                        'RaceInfo$Nkai',
                        'GradeCD',
                        'JyokenInfo$SyubetuCD',
                        'JyokenInfo$KigoCD',
                        'JyokenInfo$JyuryoCD',
                        'Kyori', 
                        'TrackCD',
                        'TenkoBaba$TenkoCD',
                        'TenkoBaba$SibaBabaCD',
                        'TenkoBaba$DirtBabaCD',
                        'Honsyokin',
                        'Fukasyokin',
                      ]
RA_df = RA_df[RA_selected_columns]
RA_df

In [ ]:
RA_df.dtypes

- Tạo hàm xử lý bảng RA

In [ ]:
def RA_process(folder_path):
    
    RA_path = folder_path + '\\RA.pickle.gz'
    RA_df = pd.read_pickle(RA_path)
    # Convert cột Key id$JyoCD
    RA_df['id$JyoCD'] = RA_df['id$JyoCD'].astype('int64')
    # Tạo cột Year
    RA_df['Year'] = RA_df['id$Year']
    # Tạo cột Month
    RA_df['Month'] = RA_df['id$MonthDay'].apply(lambda x: int(x/100))
    RA_df[['Month', 'id$MonthDay']][RA_df['Month']==12]
    # Tổng hợp giải thưởng trước trận đấu
    syokinAfter = [ 'Honsyokin$1',                
                   'Honsyokin$2',               
                'Honsyokin$3',                
                'Honsyokin$4',
                'Honsyokin$5',
                'Fukasyokin$1',
                'Fukasyokin$2',
                'Fukasyokin$3'
             ]
    syokinBefore = [ 'HonsyokinBefore$1',                
                     'HonsyokinBefore$2',               
                    'HonsyokinBefore$3',                
                    'HonsyokinBefore$4',
                    'HonsyokinBefore$5',
                    'FukasyokinBefore$1',
                    'FukasyokinBefore$2',
                    'FukasyokinBefore$3'
                   ]

    for after, before in zip(syokinAfter, syokinBefore):
        #print(after, before)
        RA_df.loc[RA_df[before]!=0, after] = RA_df[before]
    # Tạo cột mới
    RA_df['Honsyokin'] = RA_df['Honsyokin$1'] + RA_df['Honsyokin$2'] + RA_df['Honsyokin$3'] + RA_df['Honsyokin$4'] + RA_df['Honsyokin$5']
    RA_df['Fukasyokin'] = RA_df['Fukasyokin$1'] + RA_df['Fukasyokin$2'] + RA_df['Fukasyokin$3']
    
    # Select columns
    selected_columns =  ['id$Year',
                        'id$MonthDay',
                        'id$JyoCD',
                        'id$Kaiji',
                        'id$Nichiji',
                        'id$RaceNum',
                        'Year',
                        'Month',
                        'RaceInfo$TokuNum',
                        'RaceInfo$Nkai',
                        'GradeCD',
                        'JyokenInfo$SyubetuCD',
                        'JyokenInfo$KigoCD',
                        'JyokenInfo$JyuryoCD',
                        'Kyori', 
                        'TrackCD',
                        'TenkoBaba$TenkoCD',
                        'TenkoBaba$SibaBabaCD',
                        'TenkoBaba$DirtBabaCD',
                        'Honsyokin',
                        'Fukasyokin',
                      ]
    RA_df = RA_df[selected_columns]
    
    return RA_df

In [ ]:
RA_df = RA_process(folder_path)
RA_df

- SE table

In [ ]:
SE_df = pd.read_pickle(folder_path+'\\SE.pickle.gz')
SE_df[['Umaban', 'KettoNum']]

In [ ]:
# Select Columns
SE_selected_columns =  [
                        #Key
                        'id$Year',
                        'id$MonthDay',
                        'id$JyoCD',
                        'id$Kaiji',
                        'id$Nichiji',
                        'id$RaceNum',
                        #
                        'Umaban', 
                        'KettoNum',
                        'UmaKigoCD',
                        'SexCD',
                        'HinsyuCD',
                        'KeiroCD',
                        'Barei',
                        'TozaiCD',
                        'ChokyosiCode',
                        'BanusiCode',
                        'Futan',
                        'KisyuCode',
                        'MinaraiCD',
                        'BaTaijyu',
                        'ZogenFugo',
                        'ZogenSa',
                        'IJyoCD',
                        'KakuteiJyuni',
                        'Time',
                        'Odds',
                        'TimeDiff'
                       ]
SE_df = SE_df[SE_selected_columns]
SE_df

In [ ]:
SE_df.dtypes

In [ ]:
# Convert id$JyoCD
SE_df['id$JyoCD'] = SE_df['id$JyoCD'].astype('int64')

- Tạo hàm xử lý bảng SE

In [ ]:
def SE_process(folder_path):
    
    SE_path = folder_path + '\\SE.pickle.gz'
    SE_df = pd.read_pickle(SE_path)
    # Convert cột Key id$JyoCD
    SE_df['id$JyoCD'] =SE_df['id$JyoCD'].astype('int64')
 
    selected_columns =  [
                            #Key
                            'id$Year',
                            'id$MonthDay',
                            'id$JyoCD',
                            'id$Kaiji',
                            'id$Nichiji',
                            'id$RaceNum',
                            #
                            'Umaban', 
                            'KettoNum',
                            'UmaKigoCD',
                            'SexCD',
                            'HinsyuCD',
                            'KeiroCD',
                            'Barei',
                            'TozaiCD',
                            'ChokyosiCode',
                            'BanusiCode',
                            'Futan',
                            'KisyuCode',
                            'MinaraiCD',
                            'BaTaijyu',
                            'ZogenFugo',
                            'ZogenSa',
                            'IJyoCD',
                            'KakuteiJyuni',
                            'Time',
                            'Odds',
                            'TimeDiff'
                           ]
    SE_df = SE_df[selected_columns]
    SE_df.reset_index(drop=True, inplace=True)
    return SE_df

In [ ]:
SE_df = SE_process(folder_path)
SE_df

- UM table

In [ ]:
UM_df = pd.read_pickle(folder_path+'\\UM.pickle.gz')
UM_df

In [ ]:
# Select Columns
UM_selected_columns =  [
                        'KettoNum',
                        'Bamei',
                        'ZaikyuFlag',
                        'SexCD',
                        'HinsyuCD',
                        'KeiroCD',
                        'Ketto3Info$1$HansyokuNum',
                        'Ketto3Info$1$Bamei',
                        'TozaiCD',
                        'ChokyosiCode',
                        'BreederCode',  #
                        'BanusiCode',
                        'RuikeiHonsyoHeiti',
                        'RuikeiHonsyoSyogai',
                        'RuikeiFukaHeichi',
                        'RuikeiFukaSyogai',
                        'RuikeiSyutokuHeichi',
                        'RuikeiSyutokuSyogai',
                        ]
UM_df = UM_df[UM_selected_columns]
UM_df

In [ ]:
# Đổi tên các cột TozaiCD thành UM_TozaiCD
for column in UM_selected_columns:
    if column != 'KettoNum':
        new_column = 'UM_' + column
        UM_df.rename(columns={column: new_column}, inplace=True)
UM_df

- Tạo hàm xử lý bảng UM

In [ ]:
def UM_process(folder_path):
    
    UM_path = folder_path + '\\UM.pickle.gz'
    UM_df = pd.read_pickle(UM_path)
    
    # Select Columns
    selected_columns =  [
                            'KettoNum',
                            'Bamei',
                            'ZaikyuFlag',
                            'SexCD',
                            'HinsyuCD',
                            'KeiroCD',
                            'Ketto3Info$1$HansyokuNum',
                            'Ketto3Info$1$Bamei',
                            'TozaiCD',
                            'ChokyosiCode',
                            'BreederCode',  #
                            'BanusiCode',
                            'RuikeiHonsyoHeiti',
                            'RuikeiHonsyoSyogai',
                            'RuikeiFukaHeichi',
                            'RuikeiFukaSyogai',
                            'RuikeiSyutokuHeichi',
                            'RuikeiSyutokuSyogai',
                            ]
    UM_df = UM_df[selected_columns]
    # Đổi tên các cột TozaiCD thành UM_TozaiCD
    for column in selected_columns:
        if column != 'KettoNum':
            new_column = 'UM_' + column
            UM_df.rename(columns={column: new_column}, inplace=True)
            
    UM_df.reset_index(drop=True, inplace=True)
    
    return UM_df

In [ ]:
UM_df = UM_process(folder_path)
UM_df

- KS table

In [ ]:
KS_df = pd.read_pickle(folder_path+'\\KS.pickle.gz')
KS_df

In [ ]:
# Select Columns
KS_select_columns =  [
                        'KisyuCode',
                        'SexCD',
                        'SikakuCD',
                        'MinaraiCD',
                        'TozaiCD',
                        'Syotai',
                        'ChokyosiCode',
                        #'SaikinJyusyo$1$GradeCD',
                        #'SaikinJyusyo$2$GradeCD',
                        #'SaikinJyusyo$3$GradeCD',
                        
                     ]
KS_df = KS_df[KS_select_columns]
KS_df

In [ ]:
# Đổi tên các cột TozaiCD thành UM_TozaiCD
for column in KS_select_columns:
    if column != 'KisyuCode':
        new_column = 'KS_' + column
        KS_df.rename(columns={column: new_column}, inplace=True)
KS_df

- Tạo hàm xử lý bảng KS

In [ ]:
def KS_process(folder_path):
    
    KS_path = folder_path + '\\KS.pickle.gz'
    KS_df = pd.read_pickle(KS_path)
    
    # Select Columns
    select_columns =  [
                        'KisyuCode',
                        'SexCD',
                        'SikakuCD',
                        'MinaraiCD',
                        'TozaiCD',
                        'Syotai',
                        'ChokyosiCode',
                        #'SaikinJyusyo$1$GradeCD',
                        #'SaikinJyusyo$2$GradeCD',
                        #'SaikinJyusyo$3$GradeCD',
                     ]
    KS_df = KS_df[select_columns]
    # Đổi tên các cột TozaiCD thành KS_TozaiCD
    for column in select_columns:
        if column != 'KisyuCode':
            new_column = 'KS_' + column
            KS_df.rename(columns={column: new_column}, inplace=True)
    
            
    KS_df.reset_index(drop=True, inplace=True)
    
    return KS_df

In [ ]:
KS_df = KS_process(folder_path)
KS_df

- CH table

In [ ]:
CH_df = pd.read_pickle(folder_path+'\\CH.pickle.gz')
CH_df

In [ ]:
CH_df.drop_duplicates(subset=['ChokyosiCode'], keep='first', inplace=True)
CH_df

In [ ]:
# Select Columns
CH_select_columns =  [
                        'ChokyosiCode',
                        'SexCD',
                        'TozaiCD',
                        'Syotai',
                        #'SaikinJyusyo$1$GradeCD',
                        #'SaikinJyusyo$2$GradeCD',
                        #'SaikinJyusyo$3$GradeCD',
                     ]
CH_df = CH_df[CH_select_columns]
CH_df

- Đổi tên các cột trừ key

In [ ]:
for column in CH_select_columns:
    if column != 'ChokyosiCode':
        new_column = 'CH_' + column
        CH_df.rename(columns={column: new_column}, inplace=True)
CH_df

- Tạo hàm xử lý bảng CH

In [ ]:
def CH_process(folder_path):
    
    CH_path = folder_path + '\\CH.pickle.gz'
    CH_df = pd.read_pickle(CH_path)
    CH_df.drop_duplicates(subset=['ChokyosiCode'], keep='first', inplace=True)
    
    select_columns =  [
                            'ChokyosiCode',
                            'SexCD',
                            'TozaiCD',
                            'Syotai',
                            #'SaikinJyusyo$1$GradeCD',
                            #'SaikinJyusyo$2$GradeCD',
                            #'SaikinJyusyo$3$GradeCD',
                         ]
    CH_df = CH_df[select_columns]
    # Đổi tên các cột TozaiCD thành CH_TozaiCD
    for column in select_columns:
        if column != 'ChokyosiCode':
            new_column = 'CH_' + column
            CH_df.rename(columns={column: new_column}, inplace=True)
               
    CH_df.reset_index(drop=True, inplace=True)
    
    return CH_df

In [ ]:
CH_df = CH_process(folder_path)
CH_df

- HN table

In [ ]:
HN_df = pd.read_pickle(folder_path+'\\HN.pickle.gz')
HN_df

In [ ]:
HN_df.drop_duplicates(subset=['HansyokuNum'], keep='first', inplace=True)
HN_df

In [ ]:
# Select Columns
HN_selected_columns =  [
                        'HansyokuNum',
                        #'KettoNum',
                        'Bamei',
                        'SexCD',
                        'HinsyuCD',
                        'KeiroCD',
                        'HansyokuMochiKubun',
                        'HansyokuFNum',
                        'HansyokuMNum',
                        ]
HN_df = HN_df[HN_selected_columns]
HN_df

In [ ]:
# Đổi tên các cột 
for column in HN_selected_columns:
    if column != 'HansyokuNum':
        new_column = 'HN_' + column
        HN_df.rename(columns={column: new_column}, inplace=True)
HN_df

- Tạo hàm xử lý bảng HN

In [ ]:
def HN_process(folder_path):
    
    HN_path = folder_path + '\\HN.pickle.gz'
    HN_df = pd.read_pickle(HN_path)
    HN_df.drop_duplicates(subset=['HansyokuNum'], keep='first', inplace=True)
    
    selected_columns =  [
                            'HansyokuNum',
                            #'KettoNum',
                            'Bamei',
                            'SexCD',
                            'HinsyuCD',
                            'KeiroCD',
                            'HansyokuMochiKubun',
                            'HansyokuFNum',
                            'HansyokuMNum',
                            ]
    HN_df = HN_df[selected_columns]
    # Đổi tên các cột 
    for column in selected_columns:
        if column != 'HansyokuNum':
            new_column = 'HN_' + column
            HN_df.rename(columns={column: new_column}, inplace=True)
               
    HN_df.reset_index(drop=True, inplace=True)
    
    return HN_df

In [ ]:
HN_df = HN_process(folder_path)
HN_df

### 2. Merge UM và HN với key = HansyokuNum và Ketto3Info$1$HansyokuNum

In [ ]:
UM_df['HansyokuNum'] = UM_df['UM_Ketto3Info$1$HansyokuNum']

In [ ]:
# Merge 2 table
UM_HN_df = pd.merge(UM_df, HN_df, on=['HansyokuNum'], how='left')
UM_HN_df

### 3. Merge SE và UM_HN với key = KettoNum

In [ ]:
# Merge 2 table
UM_HN_SE_df = pd.merge(SE_df, UM_HN_df, on=['KettoNum'], how='left')
UM_HN_SE_df

### 3. Merge UM_HN_SE và KS với key = KisyuCode

In [ ]:
# Merge 2 table
UM_HN_SE_KS_df = pd.merge(UM_HN_SE_df, KS_df, on=['KisyuCode'], how='left')
UM_HN_SE_KS_df

### 4. Merge UM_HN_SE_KS và CH với key = ChokyosiCode

In [ ]:
# Merge 2 table
UM_HN_SE_KS_CH_df = pd.merge(UM_HN_SE_KS_df, CH_df, on=['ChokyosiCode'], how='left')
UM_HN_SE_KS_CH_df

In [ ]:
UM_HN_SE_KS_CH_df.info()

### 5. Merge UM_HN_SE_KS_CH và RA với key = ['id$Year', 'id$MonthDay', 'id$JyoCD', 'id$Kaiji', 'id$Nichiji', 'id$RaceNum']

In [ ]:
# Merge 2 table
UM_HN_SE_KS_CH_RA_df = pd.merge(RA_df, UM_HN_SE_KS_CH_df, on=['id$Year', 'id$MonthDay', 'id$JyoCD', 'id$Kaiji', 'id$Nichiji', 'id$RaceNum'],
                                how='left')
UM_HN_SE_KS_CH_RA_df

In [ ]:
UM_HN_SE_KS_CH_RA_df.info()

### 6. Cập nhập thông tin về cân nặng và thời tiết trước trận đấu

In [ ]:
WE_df = pd.read_pickle(folder_path+'\WE.pickle.gz')
WE_df = WE_df.loc[WE_df['id$JyoCD']==RA_df['id$JyoCD'].values[0], :]
WE_df

In [ ]:
UM_HN_SE_KS_CH_RA_df['TenkoBaba$TenkoCD'] = WE_df['TenkoBaba$TenkoCD'].values[0]
UM_HN_SE_KS_CH_RA_df['TenkoBaba$SibaBabaCD'] = WE_df['TenkoBaba$SibaBabaCD'].values[0]
UM_HN_SE_KS_CH_RA_df['TenkoBaba$DirtBabaCD'] = WE_df['TenkoBaba$DirtBabaCD'].values[0]
UM_HN_SE_KS_CH_RA_df['TenkoBaba$TenkoCD']

In [ ]:
WH_df = pd.read_pickle(folder_path+'\\WH.pickle.gz')
WH_df

In [ ]:
BaTaijyu_list = []
ZogenFugo_list = []
ZogenSa_list= []
for i in range(1, len(SE_df)+1):
    BaTaijyu_col = 'BataijyuInfo$' + str(i) + '$BaTaijyu'
    BaTaijyu_list.append(WH_df[BaTaijyu_col].values[0])
    ZogenFugo_col = 'BataijyuInfo$' + str(i) + '$ZogenFugo'
    ZogenFugo_list.append(WH_df[ZogenFugo_col].values[0])
    ZogenSa_col = 'BataijyuInfo$' + str(i) + '$ZogenSa'
    ZogenSa_list.append(WH_df[ZogenSa_col].values[0])
    
ZogenFugo_list

In [ ]:
UM_HN_SE_KS_CH_RA_df['BaTaijyu'] = BaTaijyu_list
UM_HN_SE_KS_CH_RA_df['ZogenFugo'] = ZogenFugo_list
UM_HN_SE_KS_CH_RA_df['ZogenSa'] = ZogenSa_list
UM_HN_SE_KS_CH_RA_df

In [ ]:
UM_HN_SE_KS_CH_RA_df[['BaTaijyu', 'ZogenFugo', 'ZogenSa']]

- Convert ZogenSa thành float dựa trên thông tin từ ZogenFugo

In [ ]:
# Kiểm tra ZogenSa'=='   '
UM_HN_SE_KS_CH_RA_df.loc[UM_HN_SE_KS_CH_RA_df['ZogenSa']=='   ', 'ZogenSa'] = 0
UM_HN_SE_KS_CH_RA_df['ZogenSa'] = UM_HN_SE_KS_CH_RA_df['ZogenSa'].astype('float64')
UM_HN_SE_KS_CH_RA_df.loc[UM_HN_SE_KS_CH_RA_df['ZogenFugo']=='-', 'ZogenSa'] = -1 * UM_HN_SE_KS_CH_RA_df['ZogenSa']
UM_HN_SE_KS_CH_RA_df['ZogenSa']

In [ ]:
# Remove trường hợp BaTaijyu = 0 vì bị cancel start
UM_HN_SE_KS_CH_RA_df = UM_HN_SE_KS_CH_RA_df[UM_HN_SE_KS_CH_RA_df['BaTaijyu']!=0]
UM_HN_SE_KS_CH_RA_df.reset_index(drop=True, inplace=True)
UM_HN_SE_KS_CH_RA_df

In [ ]:
# Drop ZogenFugo
UM_HN_SE_KS_CH_RA_df.drop('ZogenFugo', axis=1, inplace=True)
UM_HN_SE_KS_CH_RA_df

### 7. Create X_test

- Load danh sách features mới nhất

In [ ]:
import json
with open('..\\model and improve\\feature_dict.json') as js:
    feature_dict = json.load(js)
feature_dict

In [95]:
cat_col = feature_dict['cat_col']
num_col = feature_dict['num_col']
ref_col = feature_dict['ref_col']
new_col = feature_dict['new_col']
new_col

['top2_ChokyosiCode', 'top2_BanusiCode', 'top2_UM_BreederCode', 'before_Odds']

In [ ]:
id_col = ['KettoNum']
columns = id_col + cat_col + num_col + ref_col
test_data = UM_HN_SE_KS_CH_RA_df[columns]
test_data

- Tạo dữ liệu mới new_col

In [106]:
# Load train data
train_data = pd.read_csv('..\\model and improve\\train_data_best.csv')
train_data

,race_id,KettoNum,id$Year,ChokyosiCode,BanusiCode,UM_BreederCode,Odds,Kyori,TenkoBaba$DirtBabaCD_0,TenkoBaba$SibaBabaCD_0,...,KS_ChokyosiCode_365.0,id$JyoCD_1,KS_Syotai_川崎,KS_Syotai_笠松,CH_Syotai_川崎,top2_ChokyosiCode,top2_BanusiCode,top2_UM_BreederCode,before_Odds,speed
0,33769,2015103377,2017,1029,132030,400018,194,-0.560600,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,-1.347427,0.455914,0.388900,0.102339,58.468677
1,17992,2008103212,2013,411,675030,373126,443,-1.045448,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.669569,1.573814,2.089644,-0.713997,60.125261
2,3892,2006104580,2009,1065,945004,410313,503,-0.560600,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,-0.285358,0.564184,0.736131,-0.704293,58.299595
3,34437,2011105897,2017,380,382004,14,203,3.318191,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-1.267795,-0.514645,0.348900,-0.320991,53.386060
4,19817,2009100276,2013,311,813007,110031,135,3.803039,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.366346,-1.837489,-0.609051,-0.604829,52.916858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475565,4690,2006103658,2009,437,851005,103097,3717,-0.803024,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,-1.673984,-1.941640,-1.554156,1.946070,57.352941
475566,32918,2015105371,2017,422,674004,633066,699,-0.075751,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.287645,-1.306805,-0.560539,0.072635,59.198356
475567,76,2005104365,2008,1092,543008,930021,1753,-1.045448,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.827702,-0.876114,-1.207746,0.072635,58.815521
475568,796,2001100757,2008,400,450001,900018,1159,-1.045448,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,-1.065100,-0.408134,-0.174065,1.342005,59.833795
475569,24576,2011105310,2015,1056,417033,430316,1276,-1.045448,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.710732,-0.641775,0.079279,-0.441076,62.745098

In [144]:
# Lấy dữ liệu cho các new col target encoding
for code_col, value_col in zip(['ChokyosiCode', 'BanusiCode', 'UM_BreederCode'], ['top2_ChokyosiCode', 'top2_BanusiCode', 'top2_UM_BreederCode']):
    test_data[value_col] = 0
    for code in test_data[code_col]:
        try:
            value = train_data[train_data[code_col]==code][value_col].tolist()[0]
        except IndexError:
            value = 0
        test_data.loc[test_data[code_col]==code, value_col] = value
test_data['top2_UM_BreederCode']

0     2.089644
1     1.334356
2     1.334356
3    -1.192992
4    -0.600290
5     0.515134
6    -0.287621
7     0.148848
8    -0.230435
9     0.480174
10   -2.134628
11   -0.015024
12   -1.121056
13    0.000000
14   -0.486020
Name: top2_UM_BreederCode, dtype: float64

In [162]:
# Lấy dữ liệu cho before_Odds
mean_Odds = train_data['Odds'].mean()
for KettoNum in test_data['KettoNum']:
    try:
        last_KettoNum_Odds = train_data[train_data['KettoNum']==KettoNum][['race_id', 'Odds']].sort_values(by='race_id')['Odds'].tolist()[-1]
    except IndexError:
        last_KettoNum_Odds = mean_Odds
    test_data.loc[test_data['KettoNum']==KettoNum, 'before_Odds'] = last_KettoNum_Odds
test_data

,KettoNum,Month,id$JyoCD,GradeCD,JyokenInfo$SyubetuCD,JyokenInfo$KigoCD,JyokenInfo$JyuryoCD,TrackCD,TenkoBaba$TenkoCD,TenkoBaba$SibaBabaCD,...,BaTaijyu,ZogenSa,ChokyosiCode,BanusiCode,UM_BreederCode,Odds,top2_ChokyosiCode,top2_BanusiCode,top2_UM_BreederCode,before_Odds
0,2016104464,12,6,,11,023,3,24,1,1,...,440,4.0,1153,226800,373126,0,-0.048223,1.479173,2.089644,667.134931
1,2016105215,12,6,,11,023,3,24,1,1,...,446,4.0,1102,364030,393126,0,0.541593,1.149987,1.334356,667.134931
2,2016105205,12,6,,11,023,3,24,1,1,...,510,2.0,1163,148800,393126,0,0.000000,0.648926,1.334356,667.134931
3,2016100976,12,6,,11,023,3,24,1,1,...,430,-8.0,1023,799033,500318,0,-0.251643,0.000000,-1.192992,667.134931
4,2016103007,12,6,,11,023,3,24,1,1,...,424,6.0,1024,608033,935496,0,-0.876749,-0.246789,-0.600290,667.134931
5,2016106271,12,6,,11,023,3,24,1,1,...,446,6.0,383,380800,303305,0,-0.529024,-0.778969,0.515134,667.134931
6,2016105531,12,6,,11,023,3,24,1,1,...,452,-2.0,1023,854800,233071,0,-0.251643,0.446587,-0.287621,667.134931
7,2016104169,12,6,,11,023,3,24,1,1,...,448,-8.0,402,149007,203374,0,-1.013388,-0.538071,0.148848,667.134931
8,2016101100,12,6,,11,023,3,24,1,1,...,444,6.0,1080,623033,433091,0,-0.328853,-0.451534,-0.230435,667.134931
9,2016102918,12,6,,11,023,3,24,1,1,...,460,0.0,1097,935800,803353,0,1.142913,0.648381,0.480174,667.134931
10,2016104154,12,6,,11,023,3,24,1,1,...,438,12.0,435,784800,500384,0,-0.461246,-1.798476,-2.134628,667.134931
11,2016100354,12,6,,11,023,3,24,1,1,...,480,-2.0,417,163002,800338,0,-0.766638,-0.590500,-0.015024,667.134931
12,2016102793,12,6,,11,023,3,24,1,1,...,412,0.0,1089,797008,503341,0,-0.703419,-0.799150,-1.121056,667.134931
13,2016103522,12,6,,11,023,3,24,1,1,...,454,6.0,1031,619002,510320,0,-0.931807,-0.312665,0.000000,667.134931
14,2016100216,12,6,,11,023,3,24,1,1,...,452,4.0,1094,515800,510339,0,-0.509992,0.524293,-0.486020,667.134931

- Transform X_test

In [156]:
import joblib 
enc = joblib.load('..\\model and improve\\enc.bin')
scaler = joblib.load('..\\model and improve\\scaler.bin')
scaler

StandardScaler()

In [163]:
cat_feature_names = enc.get_feature_names(cat_col)
cat_feature_names

X_test_cat = test_data[cat_col]
X_test_cat = enc.transform(X_test_cat).toarray()
X_test_cat

X_test_cat = pd.DataFrame(X_test_cat, columns=cat_feature_names)
X_test_cat

new_num_col = num_col+new_col
X_test_num = test_data[new_num_col]
X_scale = scaler.transform(X_test_num)
X_test_num = pd.DataFrame(X_scale, columns=new_num_col)
X_test_num

X_test = pd.concat([X_test_cat, X_test_num], axis=1, sort=False)
X_test

,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6,Month_7,Month_8,Month_9,Month_10,...,Honsyokin,Fukasyokin,Barei,Futan,BaTaijyu,ZogenSa,top2_ChokyosiCode,top2_BanusiCode,top2_UM_BreederCode,before_Odds
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,-1.006550,0.570327,-3.947144,30.515140,50.918226,0.075817
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-2.309705,-0.805789,0.570327,8.400722,22.998891,31.172711,0.075817
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,1.335652,0.263741,-2.937596,11.558258,31.172711,0.075817
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-2.309705,-1.341150,-1.269192,-8.205769,-3.258558,-34.899800,0.075817
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,-1.541910,0.876914,-21.292454,-8.893443,-19.404781,0.075817
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-1.163857,-0.805789,0.876914,-14.012797,-21.044609,9.755781,0.075817
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,-0.605029,-0.349432,-8.205769,6.938291,-11.230675,0.075817
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,-0.738869,-1.269192,-24.153020,-15.544228,0.179951,0.075817
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,-0.872709,0.876914,-9.822172,-13.568344,-9.735656,0.075817
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,-0.337349,-0.042846,20.989455,11.545811,8.841824,0.075817
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,-1.073470,1.796673,-12.593839,-44.322832,-59.517010,0.075817
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,0.331851,-0.349432,-18.987263,-16.741332,-4.104160,0.075817
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-1.163857,-1.943430,-0.042846,-17.663774,-21.505401,-33.019167,0.075817
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,-0.538109,0.876914,-22.445115,-10.397572,-3.711381,0.075817
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.776299,-0.530241,-1.229713,-0.590933,-0.605029,0.570327,-13.614345,8.712526,-16.417424,0.075817

- Update dữ liệu mới vào dữ liệu đã chọn feature tự động

In [184]:
extract_feature = feature_dict['extract_feature']
new_extract_feature = extract_feature + new_col
X_test = X_test[new_extract_feature]
X_test

,Kyori,TenkoBaba$DirtBabaCD_0,TenkoBaba$SibaBabaCD_0,TenkoBaba$SibaBabaCD_1,TenkoBaba$DirtBabaCD_1,id$RaceNum,TrackCD_52,TrackCD_17,JyokenInfo$SyubetuCD_18,GradeCD_,...,KS_Syotai_フランス,KS_ChokyosiCode_365.0,id$JyoCD_1,KS_Syotai_川崎,KS_Syotai_笠松,CH_Syotai_川崎,top2_ChokyosiCode,top2_BanusiCode,top2_UM_BreederCode,before_Odds
0,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.048223,1.479173,2.089644,0.075817
1,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.541593,1.149987,1.334356,0.075817
2,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.648926,1.334356,0.075817
3,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.251643,0.000000,-1.192992,0.075817
4,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.876749,-0.246789,-0.600290,0.075817
5,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.529024,-0.778969,0.515134,0.075817
6,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.251643,0.446587,-0.287621,0.075817
7,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.013388,-0.538071,0.148848,0.075817
8,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.328853,-0.451534,-0.230435,0.075817
9,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.142913,0.648381,0.480174,0.075817
10,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.461246,-1.798476,-2.134628,0.075817
11,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.766638,-0.590500,-0.015024,0.075817
12,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.703419,-0.799150,-1.121056,0.075817
13,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.931807,-0.312665,0.000000,0.075817
14,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.509992,0.524293,-0.486020,0.075817

In [185]:
# Thay giá trị target encoding 
for col in ['top2_ChokyosiCode', 'top2_BanusiCode', 'top2_UM_BreederCode']:
    X_test[col] = test_data[col]
X_test

,Kyori,TenkoBaba$DirtBabaCD_0,TenkoBaba$SibaBabaCD_0,TenkoBaba$SibaBabaCD_1,TenkoBaba$DirtBabaCD_1,id$RaceNum,TrackCD_52,TrackCD_17,JyokenInfo$SyubetuCD_18,GradeCD_,...,KS_Syotai_フランス,KS_ChokyosiCode_365.0,id$JyoCD_1,KS_Syotai_川崎,KS_Syotai_笠松,CH_Syotai_川崎,top2_ChokyosiCode,top2_BanusiCode,top2_UM_BreederCode,before_Odds
0,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.048223,1.479173,2.089644,0.075817
1,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.541593,1.149987,1.334356,0.075817
2,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.648926,1.334356,0.075817
3,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.251643,0.000000,-1.192992,0.075817
4,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.876749,-0.246789,-0.600290,0.075817
5,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.529024,-0.778969,0.515134,0.075817
6,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.251643,0.446587,-0.287621,0.075817
7,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.013388,-0.538071,0.148848,0.075817
8,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.328853,-0.451534,-0.230435,0.075817
9,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.142913,0.648381,0.480174,0.075817
10,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.461246,-1.798476,-2.134628,0.075817
11,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.766638,-0.590500,-0.015024,0.075817
12,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.703419,-0.799150,-1.121056,0.075817
13,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.931807,-0.312665,0.000000,0.075817
14,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.509992,0.524293,-0.486020,0.075817

- Tạo hàm process  test data (Client side)

In [186]:

def create_new_race_data(folder_path):
    # Load tables
    RA_df = RA_process(folder_path)
    SE_df = SE_process(folder_path)
    UM_df = UM_process(folder_path)
    KS_df = KS_process(folder_path)
    CH_df = CH_process(folder_path)
    HN_df = HN_process(folder_path)
        
    # Merge tables
    UM_df['HansyokuNum'] = UM_df['UM_Ketto3Info$1$HansyokuNum']
    # Merge 2 table UM, HN
    UM_HN_df = pd.merge(UM_df, HN_df, on=['HansyokuNum'], how='left')
    # 
    UM_HN_SE_df = pd.merge(SE_df, UM_HN_df, on=['KettoNum'], how='left')
    #
    UM_HN_SE_KS_df = pd.merge(UM_HN_SE_df, KS_df, on=['KisyuCode'], how='left')
    #
    UM_HN_SE_KS_CH_df = pd.merge(UM_HN_SE_KS_df, CH_df, on=['ChokyosiCode'], how='left')
    #
    UM_HN_SE_KS_CH_RA_df = pd.merge(RA_df, UM_HN_SE_KS_CH_df, on=['id$Year', 'id$MonthDay', 'id$JyoCD', 'id$Kaiji', 'id$Nichiji', 'id$RaceNum'], how='left')
    final_df = UM_HN_SE_KS_CH_RA_df.copy()
    
    # Update information from WE and WH tables
    WE_df = pd.read_pickle(folder_path+'\\WE.pickle.gz')
    WE_df = WE_df.loc[WE_df['id$JyoCD']==RA_df['id$JyoCD'].values[0], :]
    
    final_df['TenkoBaba$TenkoCD'] = WE_df['TenkoBaba$TenkoCD'].values[0]
    final_df['TenkoBaba$SibaBabaCD'] = WE_df['TenkoBaba$SibaBabaCD'].values[0]
    final_df['TenkoBaba$DirtBabaCD'] = WE_df['TenkoBaba$DirtBabaCD'].values[0]
    
    WH_df = pd.read_pickle(folder_path+'\\WH.pickle.gz')
    BaTaijyu_list = []
    ZogenFugo_list = []
    ZogenSa_list= []
    for i in range(1, len(SE_df)+1):
        BaTaijyu_col = 'BataijyuInfo$' + str(i) + '$BaTaijyu'
        BaTaijyu_list.append(WH_df[BaTaijyu_col].values[0])
        ZogenFugo_col = 'BataijyuInfo$' + str(i) + '$ZogenFugo'
        ZogenFugo_list.append(WH_df[ZogenFugo_col].values[0])
        ZogenSa_col = 'BataijyuInfo$' + str(i) + '$ZogenSa'
        ZogenSa_list.append(WH_df[ZogenSa_col].values[0])
        
    final_df['BaTaijyu'] = BaTaijyu_list
    final_df['ZogenFugo'] = ZogenFugo_list
    final_df['ZogenSa'] = ZogenSa_list
    
    # Convert  ZogenSa 
    final_df.loc[final_df['ZogenSa']=='   ', 'ZogenSa'] = 0
    final_df['ZogenSa'] = final_df['ZogenSa'].astype('float64')
    final_df.loc[final_df['ZogenFugo']=='-', 'ZogenSa'] = -1 * final_df['ZogenSa']
    final_df['ZogenSa']
    
    # Remove trường hợp BaTaijyu = 0 vì bị cancel start
    final_df = final_df[final_df['BaTaijyu']!=0]
    final_df.reset_index(drop=True, inplace=True)
    # Drop ZogenFugo
    final_df.drop('ZogenFugo', axis=1, inplace=True)
   
    # Select columns
    import json
    with open('..\\model and improve\\feature_dict.json') as js:
        feature_dict = json.load(js)
    cat_col = feature_dict['cat_col']
    num_col = feature_dict['num_col']
    ref_col = feature_dict['ref_col']
    
    id_col = ['KettoNum']
    columns = id_col + cat_col + num_col + ref_col
    test_data  = final_df[columns]
    
    return test_data

In [187]:
test_data = create_new_race_data(folder_path)
test_data

,KettoNum,Month,id$JyoCD,GradeCD,JyokenInfo$SyubetuCD,JyokenInfo$KigoCD,JyokenInfo$JyuryoCD,TrackCD,TenkoBaba$TenkoCD,TenkoBaba$SibaBabaCD,...,Honsyokin,Fukasyokin,Barei,Futan,BaTaijyu,ZogenSa,ChokyosiCode,BanusiCode,UM_BreederCode,Odds
0,2016104464,12,6,,11,023,3,24,1,1,...,95500,0,2,540,440,4.0,1153,226800,373126,0
1,2016105215,12,6,,11,023,3,24,1,1,...,95500,0,2,510,446,4.0,1102,364030,393126,0
2,2016105205,12,6,,11,023,3,24,1,1,...,95500,0,2,540,510,2.0,1163,148800,393126,0
3,2016100976,12,6,,11,023,3,24,1,1,...,95500,0,2,510,430,-8.0,1023,799033,500318,0
4,2016103007,12,6,,11,023,3,24,1,1,...,95500,0,2,540,424,6.0,1024,608033,935496,0
5,2016106271,12,6,,11,023,3,24,1,1,...,95500,0,2,530,446,6.0,383,380800,303305,0
6,2016105531,12,6,,11,023,3,24,1,1,...,95500,0,2,540,452,-2.0,1023,854800,233071,0
7,2016104169,12,6,,11,023,3,24,1,1,...,95500,0,2,540,448,-8.0,402,149007,203374,0
8,2016101100,12,6,,11,023,3,24,1,1,...,95500,0,2,540,444,6.0,1080,623033,433091,0
9,2016102918,12,6,,11,023,3,24,1,1,...,95500,0,2,540,460,0.0,1097,935800,803353,0
10,2016104154,12,6,,11,023,3,24,1,1,...,95500,0,2,540,438,12.0,435,784800,500384,0
11,2016100354,12,6,,11,023,3,24,1,1,...,95500,0,2,540,480,-2.0,417,163002,800338,0
12,2016102793,12,6,,11,023,3,24,1,1,...,95500,0,2,530,412,0.0,1089,797008,503341,0
13,2016103522,12,6,,11,023,3,24,1,1,...,95500,0,2,540,454,6.0,1031,619002,510320,0
14,2016100216,12,6,,11,023,3,24,1,1,...,95500,0,2,540,452,4.0,1094,515800,510339,0

- Tạo hàm transform  test data (Server side)

In [188]:
import joblib
import json
import pandas as pd
import numpy as np

def transform_new_race_data(train_data, test_data):
    
    # Lấy dữ liệu cho các new col target encoding
    for code_col, value_col in zip(['ChokyosiCode', 'BanusiCode', 'UM_BreederCode'], ['top2_ChokyosiCode', 'top2_BanusiCode', 'top2_UM_BreederCode']):
        test_data[value_col] = 0
        for code in test_data[code_col]:
            try:
                value = train_data[train_data[code_col]==code][value_col].tolist()[0]
            except IndexError:
                value = 0
            test_data.loc[test_data[code_col]==code, value_col] = value
            
     # Lấy dữ liệu cho before_Odds
    mean_Odds = train_data['Odds'].mean()
    for KettoNum in test_data['KettoNum']:
        try:
            last_KettoNum_Odds = train_data[train_data['KettoNum']==KettoNum][['race_id', 'Odds']].sort_values(by='race_id')['Odds'].tolist()[-1]
        except IndexError:
            last_KettoNum_Odds = mean_Odds
        test_data.loc[test_data['KettoNum']==KettoNum, 'before_Odds'] = last_KettoNum_Odds       
    
    import joblib 
    enc = joblib.load('..\\model and improve\\enc.bin')
    scaler = joblib.load('..\\model and improve\\scaler.bin')
    
    import json
    with open('..\\model and improve\\feature_dict.json') as js:
        feature_dict = json.load(js)
    cat_col = feature_dict['cat_col']
    num_col = feature_dict['num_col']
    new_col = feature_dict['new_col']
    ref_col = feature_dict['ref_col'] # ['ChokyosiCode', 'BanusiCode', 'UM_BreederCode', 'Odds']
    
    cat_feature_names = enc.get_feature_names(cat_col)
    X_test_cat = test_data[cat_col]
    X_test_cat = enc.transform(X_test_cat).toarray()
    X_test_cat = pd.DataFrame(X_test_cat, columns=cat_feature_names)
    new_num_col = num_col + new_col
    X_test_num = test_data[new_num_col]
    X_scale = scaler.transform(X_test_num)
    X_test_num = pd.DataFrame(X_scale, columns=new_num_col)
    X_test = pd.concat([X_test_cat, X_test_num], axis=1, sort=False)
    
    extract_feature = feature_dict['extract_feature']
    new_extract_feature = extract_feature + new_col
    X_test = X_test[new_extract_feature]
    
    # Thay giá trị target encoding 
    for col in ['top2_ChokyosiCode', 'top2_BanusiCode', 'top2_UM_BreederCode']:
        X_test[col] = test_data[col]
    
    return X_test

In [189]:
ttt = transform_new_race_data(train_data, test_data)
ttt

,Kyori,TenkoBaba$DirtBabaCD_0,TenkoBaba$SibaBabaCD_0,TenkoBaba$SibaBabaCD_1,TenkoBaba$DirtBabaCD_1,id$RaceNum,TrackCD_52,TrackCD_17,JyokenInfo$SyubetuCD_18,GradeCD_,...,KS_Syotai_フランス,KS_ChokyosiCode_365.0,id$JyoCD_1,KS_Syotai_川崎,KS_Syotai_笠松,CH_Syotai_川崎,top2_ChokyosiCode,top2_BanusiCode,top2_UM_BreederCode,before_Odds
0,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.048223,1.479173,2.089644,0.075817
1,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.541593,1.149987,1.334356,0.075817
2,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.648926,1.334356,0.075817
3,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.251643,0.000000,-1.192992,0.075817
4,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.876749,-0.246789,-0.600290,0.075817
5,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.529024,-0.778969,0.515134,0.075817
6,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.251643,0.446587,-0.287621,0.075817
7,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.013388,-0.538071,0.148848,0.075817
8,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.328853,-0.451534,-0.230435,0.075817
9,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.142913,0.648381,0.480174,0.075817
10,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.461246,-1.798476,-2.134628,0.075817
11,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.766638,-0.590500,-0.015024,0.075817
12,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.703419,-0.799150,-1.121056,0.075817
13,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.931807,-0.312665,0.000000,0.075817
14,-1.045448,0.0,0.0,1.0,0.0,-1.550193,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.509992,0.524293,-0.486020,0.075817