## Lấy dữ liệu tại bảng BN

In [1]:
import pandas as pd
import numpy as np

- Get data path

In [2]:
import os.path as path
data_path =  path.abspath(path.join('' ,"../../data/historical_data"))
data_path = data_path + '\\BN.pickle.gz'
data_path

'D:\\Funix_FPT\\DataScience\\Final_Project\\horse_race_project\\data\\historical_data\\BN.pickle.gz'

In [3]:
BN_df = pd.read_pickle(data_path)
BN_df

,filename,line_no,head$RecordSpec,head$DataKubun,head$MakeDate$Year,head$MakeDate$Month,head$MakeDate$Day,BanusiCode,BanusiName_Co,BanusiName,...,HonRuikei$2$SetYear,HonRuikei$2$HonSyokinTotal,HonRuikei$2$FukaSyokin,HonRuikei$2$ChakuKaisu$1,HonRuikei$2$ChakuKaisu$2,HonRuikei$2$ChakuKaisu$3,HonRuikei$2$ChakuKaisu$4,HonRuikei$2$ChakuKaisu$5,HonRuikei$2$ChakuKaisu$6,crlf
0,BNFW2018051420180514133247.json,1,BN,2,2018,5,14,2803,株式会社 キーファーズ,キーファーズ,...,0,1617000,1520,12,19,13,8,11,64,\r\n
1,BNFW2018051420180514133247.json,2,BN,2,2018,5,14,3060,ゴドルフィン,ゴドルフィン,...,0,69600850,625440,401,342,318,278,251,1940,\r\n
2,BNFW2018051420180514133247.json,3,BN,2,2018,5,14,4800,名古屋競馬 株式会社,名古屋競馬,...,0,6146450,48326,34,39,34,30,28,315,\r\n
3,BNFW2018051420180514133247.json,4,BN,2,2018,5,14,5803,株式会社 キャピタル・システム,キャピタル・システム,...,0,8614700,179090,39,37,27,21,26,258,\r\n
4,BNFW2018051420180514133247.json,5,BN,2,2018,5,14,6030,佐々木 主浩,佐々木 主浩,...,0,21567600,488200,51,25,29,18,25,153,\r\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8992,BNFW2018052120180521133118.json,470,BN,2,2018,5,21,979033,永井 宏明,永井 宏明,...,0,1177200,6810,2,4,16,13,9,100,\r\n
8993,BNFW2018052120180521133118.json,471,BN,2,2018,5,21,982033,尾上 寿夫,尾上 寿夫,...,0,25500,0,0,0,1,1,0,13,\r\n
8994,BNFW2018052120180521133118.json,472,BN,2,2018,5,21,985001,小林 百太郎,小林 百太郎,...,0,54510100,446895,265,282,225,213,220,1790,\r\n
8995,BNFW2018052120180521133118.json,473,BN,2,2018,5,21,993033,梅澤 明,梅澤 明,...,0,165500,0,0,3,3,3,3,4,\r\n
8996,BNFW2018052120180521133118.json,474,BN,2,2018,5,21,994002,飯田 正剛,飯田 正剛,...,0,27064550,514610,155,173,133,165,168,1547,\r\n

In [2]:
BN_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8997 entries, 0 to 8996
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   filename                    8997 non-null   object
 1   line_no                     8997 non-null   int64
 2   head$RecordSpec             8997 non-null   object
 3   head$DataKubun              8997 non-null   int64
 4   head$MakeDate$Year          8997 non-null   int64
 5   head$MakeDate$Month         8997 non-null   int64
 6   head$MakeDate$Day           8997 non-null   int64
 7   BanusiCode                  8997 non-null   int64
 8   BanusiName_Co               8997 non-null   object
 9   BanusiName                  8997 non-null   object
 10  BanusiNameKana              8997 non-null   object
 11  BanusiNameEng               8997 non-null   object
 12  Fukusyoku                   8997 non-null   object
 13  HonRuikei$1$SetYear         8997 non-null   int64
 14  HonRuikei$1$HonSyokinTotal  8997 non-null   int64
 15  HonRuikei$1$FukaSyokin      8997 non-null   int64
 16  HonRuikei$1$ChakuKaisu$1    8997 non-null   int64
 17  HonRuikei$1$ChakuKaisu$2    8997 non-null   int64
 18  HonRuikei$1$ChakuKaisu$3    8997 non-null   int64
 19  HonRuikei$1$ChakuKaisu$4    8997 non-null   int64
 20  HonRuikei$1$ChakuKaisu$5    8997 non-null   int64
 21  HonRuikei$1$ChakuKaisu$6    8997 non-null   int64
 22  HonRuikei$2$SetYear         8997 non-null   int64
 23  HonRuikei$2$HonSyokinTotal  8997 non-null   int64
 24  HonRuikei$2$FukaSyokin      8997 non-null   int64
 25  HonRuikei$2$ChakuKaisu$1    8997 non-null   int64
 26  HonRuikei$2$ChakuKaisu$2    8997 non-null   int64
 27  HonRuikei$2$ChakuKaisu$3    8997 non-null   int64
 28  HonRuikei$2$ChakuKaisu$4    8997 non-null   int64
 29  HonRuikei$2$ChakuKaisu$5    8997 non-null   int64
 30  HonRuikei$2$ChakuKaisu$6    8997 non-null   int64
 31  crlf                        8997 non-null   object
dtypes: int64(24), object(8)
memory usage: 2.2+ MB

In [2]:
for c in BN_df.columns:
    print(c)

filename
line_no
head$RecordSpec
head$DataKubun
head$MakeDate$Year
head$MakeDate$Month
head$MakeDate$Day
BanusiCode
BanusiName_Co
BanusiName
BanusiNameKana
BanusiNameEng
Fukusyoku
HonRuikei$1$SetYear
HonRuikei$1$HonSyokinTotal
HonRuikei$1$FukaSyokin
HonRuikei$1$ChakuKaisu$1
HonRuikei$1$ChakuKaisu$2
HonRuikei$1$ChakuKaisu$3
HonRuikei$1$ChakuKaisu$4
HonRuikei$1$ChakuKaisu$5
HonRuikei$1$ChakuKaisu$6
HonRuikei$2$SetYear
HonRuikei$2$HonSyokinTotal
HonRuikei$2$FukaSyokin
HonRuikei$2$ChakuKaisu$1
HonRuikei$2$ChakuKaisu$2
HonRuikei$2$ChakuKaisu$3
HonRuikei$2$ChakuKaisu$4
HonRuikei$2$ChakuKaisu$5
HonRuikei$2$ChakuKaisu$6
crlf

In [3]:
BN_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8997 entries, 0 to 8996
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   filename                    8997 non-null   object
 1   line_no                     8997 non-null   int64
 2   head$RecordSpec             8997 non-null   object
 3   head$DataKubun              8997 non-null   int64
 4   head$MakeDate$Year          8997 non-null   int64
 5   head$MakeDate$Month         8997 non-null   int64
 6   head$MakeDate$Day           8997 non-null   int64
 7   BanusiCode                  8997 non-null   int64
 8   BanusiName_Co               8997 non-null   object
 9   BanusiName                  8997 non-null   object
 10  BanusiNameKana              8997 non-null   object
 11  BanusiNameEng               8997 non-null   object
 12  Fukusyoku                   8997 non-null   object
 13  HonRuikei$1$SetYear         8997 non-null   int64
 14  HonRuikei$1$HonSyokinTotal  8997 non-null   int64
 15  HonRuikei$1$FukaSyokin      8997 non-null   int64
 16  HonRuikei$1$ChakuKaisu$1    8997 non-null   int64
 17  HonRuikei$1$ChakuKaisu$2    8997 non-null   int64
 18  HonRuikei$1$ChakuKaisu$3    8997 non-null   int64
 19  HonRuikei$1$ChakuKaisu$4    8997 non-null   int64
 20  HonRuikei$1$ChakuKaisu$5    8997 non-null   int64
 21  HonRuikei$1$ChakuKaisu$6    8997 non-null   int64
 22  HonRuikei$2$SetYear         8997 non-null   int64
 23  HonRuikei$2$HonSyokinTotal  8997 non-null   int64
 24  HonRuikei$2$FukaSyokin      8997 non-null   int64
 25  HonRuikei$2$ChakuKaisu$1    8997 non-null   int64
 26  HonRuikei$2$ChakuKaisu$2    8997 non-null   int64
 27  HonRuikei$2$ChakuKaisu$3    8997 non-null   int64
 28  HonRuikei$2$ChakuKaisu$4    8997 non-null   int64
 29  HonRuikei$2$ChakuKaisu$5    8997 non-null   int64
 30  HonRuikei$2$ChakuKaisu$6    8997 non-null   int64
 31  crlf                        8997 non-null   object
dtypes: int64(24), object(8)
memory usage: 2.2+ MB