## Lấy dữ liệu tại bảng UM

In [1]:
import pandas as pd
import numpy as np
from collections import Counter

- Get data path

In [2]:
import os.path as path
data_path =  path.abspath(path.join('' ,"../../data/historical_data"))
data_path = data_path + '\\UM.pickle.gz'
data_path

'D:\\Funix_FPT\\DataScience\\Final_Project\\horse_race_project\\data\\historical_data\\UM.pickle.gz'

In [3]:
UM_df = pd.read_pickle(data_path)
UM_df

,filename,line_no,head$RecordSpec,head$DataKubun,head$MakeDate$Year,head$MakeDate$Month,head$MakeDate$Day,KettoNum,DelKubun,RegDate$Year,...,ChakuKaisuKyori$6$Chakukaisu$3,ChakuKaisuKyori$6$Chakukaisu$4,ChakuKaisuKyori$6$Chakukaisu$5,ChakuKaisuKyori$6$Chakukaisu$6,Kyakusitu$1,Kyakusitu$2,Kyakusitu$3,Kyakusitu$4,RaceCount,crlf
0,UMXM2018049920180430153312.json,1,UM,4,2014,12,22,2009102487,1,2011,...,0,0,0,0,0,4,2,1,11,\r\n
1,UMXM2018049920180430153312.json,2,UM,4,2017,2,6,2009102488,1,2012,...,0,0,0,0,0,1,1,1,15,\r\n
2,UMXM2018049920180430153312.json,3,UM,4,2013,5,28,2009102489,1,2011,...,0,0,0,0,0,0,1,2,8,\r\n
3,UMXM2018049920180430153312.json,4,UM,9,2012,3,29,2009102490,1,2012,...,0,0,0,0,0,1,1,0,2,\r\n
4,UMXM2018049920180430153312.json,5,UM,4,2016,12,5,2009102491,1,2011,...,0,0,1,0,2,4,6,6,25,\r\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178837,UMFW2018050720180507133121.json,1574,UM,4,2018,5,7,2016106534,0,2017,...,0,0,0,0,0,0,0,0,0,\r\n
178838,UMFW2018050720180507133121.json,1575,UM,4,2018,5,7,2016106576,0,2018,...,0,0,0,0,0,0,0,0,0,\r\n
178839,UMFW2018050720180507133121.json,1576,UM,1,2018,5,7,2016109023,0,2018,...,0,0,0,0,0,0,0,0,0,\r\n
178840,UMFW2018050720180507133121.json,1577,UM,1,2018,5,7,2016110041,0,2018,...,0,0,0,0,0,0,0,0,0,\r\n
178841,UMFW2018050720180507133121.json,1578,UM,1,2018,5,7,2016110091,0,2018,...,0,0,0,0,0,0,0,0,0,\r\n

### 1. Kiểm tra dữ liệu

In [5]:
UM_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178842 entries, 0 to 178841
Columns: 238 entries, filename to crlf
dtypes: int64(212), object(26)
memory usage: 324.7+ MB

In [15]:
for c, d in zip(UM_df.columns, UM_df.dtypes):
    print(c, (25-len(c))*' ',d)

filename                   object
line_no                    int64
head$RecordSpec            object
head$DataKubun             int64
head$MakeDate$Year         int64
head$MakeDate$Month        int64
head$MakeDate$Day          int64
KettoNum                   int64
DelKubun                   int64
RegDate$Year               int64
RegDate$Month              int64
RegDate$Day                int64
DelDate$Year               int64
DelDate$Month              int64
DelDate$Day                int64
BirthDate$Year             int64
BirthDate$Month            int64
BirthDate$Day              int64
Bamei                      object
BameiKana                  object
BameiEng                   object
ZaikyuFlag                 int64
Reserved                   object
UmaKigoCD                  int64
SexCD                      int64
HinsyuCD                   int64
KeiroCD                    int64
Ketto3Info$1$HansyokuNum   int64
Ketto3Info$1$Bamei         object
Ketto3Info$2$HansyokuNum   int64
Ketto3Info$2$Bamei         object
Ketto3Info$3$HansyokuNum   int64
Ketto3Info$3$Bamei         object
Ketto3Info$4$HansyokuNum   int64
Ketto3Info$4$Bamei         object
Ketto3Info$5$HansyokuNum   int64
Ketto3Info$5$Bamei         object
Ketto3Info$6$HansyokuNum   int64
Ketto3Info$6$Bamei         object
Ketto3Info$7$HansyokuNum   int64
Ketto3Info$7$Bamei         object
Ketto3Info$8$HansyokuNum   int64
Ketto3Info$8$Bamei         object
Ketto3Info$9$HansyokuNum   int64
Ketto3Info$9$Bamei         object
Ketto3Info$10$HansyokuNum  int64
Ketto3Info$10$Bamei        object
Ketto3Info$11$HansyokuNum  int64
Ketto3Info$11$Bamei        object
Ketto3Info$12$HansyokuNum  int64
Ketto3Info$12$Bamei        object
Ketto3Info$13$HansyokuNum  int64
Ketto3Info$13$Bamei        object
Ketto3Info$14$HansyokuNum  int64
Ketto3Info$14$Bamei        object
TozaiCD                    int64
ChokyosiCode               int64
ChokyosiRyakusyo           object
Syotai                     object
BreederCode                int64
BreederName                object
SanchiName                 object
BanusiCode                 int64
BanusiName                 object
RuikeiHonsyoHeiti          int64
RuikeiHonsyoSyogai         int64
RuikeiFukaHeichi           int64
RuikeiFukaSyogai           int64
RuikeiSyutokuHeichi        int64
RuikeiSyutokuSyogai        int64
ChakuSogo$Chakukaisu$1     int64
ChakuSogo$Chakukaisu$2     int64
ChakuSogo$Chakukaisu$3     int64
ChakuSogo$Chakukaisu$4     int64
ChakuSogo$Chakukaisu$5     int64
ChakuSogo$Chakukaisu$6     int64
ChakuChuo$Chakukaisu$1     int64
ChakuChuo$Chakukaisu$2     int64
ChakuChuo$Chakukaisu$3     int64
ChakuChuo$Chakukaisu$4     int64
ChakuChuo$Chakukaisu$5     int64
ChakuChuo$Chakukaisu$6     int64
ChakuKaisuBa$1$Chakukaisu$1  int64
ChakuKaisuBa$1$Chakukaisu$2  int64
ChakuKaisuBa$1$Chakukaisu$3  int64
ChakuKaisuBa$1$Chakukaisu$4  int64
ChakuKaisuBa$1$Chakukaisu$5  int64
ChakuKaisuBa$1$Chakukaisu$6  int64
ChakuKaisuBa$2$Chakukaisu$1  int64
ChakuKaisuBa$2$Chakukaisu$2  int64
ChakuKaisuBa$2$Chakukaisu$3  int64
ChakuKaisuBa$2$Chakukaisu$4  int64
ChakuKaisuBa$2$Chakukaisu$5  int64
ChakuKaisuBa$2$Chakukaisu$6  int64
ChakuKaisuBa$3$Chakukaisu$1  int64
ChakuKaisuBa$3$Chakukaisu$2  int64
ChakuKaisuBa$3$Chakukaisu$3  int64
ChakuKaisuBa$3$Chakukaisu$4  int64
ChakuKaisuBa$3$Chakukaisu$5  int64
ChakuKaisuBa$3$Chakukaisu$6  int64
ChakuKaisuBa$4$Chakukaisu$1  int64
ChakuKaisuBa$4$Chakukaisu$2  int64
ChakuKaisuBa$4$Chakukaisu$3  int64
ChakuKaisuBa$4$Chakukaisu$4  int64
ChakuKaisuBa$4$Chakukaisu$5  int64
ChakuKaisuBa$4$Chakukaisu$6  int64
ChakuKaisuBa$5$Chakukaisu$1  int64
ChakuKaisuBa$5$Chakukaisu$2  int64
ChakuKaisuBa$5$Chakukaisu$3  int64
ChakuKaisuBa$5$Chakukaisu$4  int64
ChakuKaisuBa$5$Chakukaisu$5  int64
ChakuKaisuBa$5$Chakukaisu$6  int64
ChakuKaisuBa$6$Chakukaisu$1  int64
ChakuKaisuBa$6$Chakukaisu$2  int64
ChakuKaisuBa$6$Chakukaisu$3  int64
ChakuKaisuBa$6$Chakukaisu$4  int64
ChakuKaisuBa$6$Chakukaisu$5  int64
ChakuKaisuBa$6$Chakukaisu$6  int64
ChakuKaisuBa$7$Chakukaisu$1  int64
ChakuKaisuBa$7$Chakukaisu$2  int64
ChakuKaisuBa$7$Chakukaisu$3  int64
ChakuKaisuBa$7$Chakukaisu$4  int64
ChakuKaisuBa$7$Chakukaisu$5  int64
ChakuKaisuBa$7$Chakukaisu$6  int64
ChakuKaisuJyotai$1$Chakukaisu$1  int64
ChakuKaisuJyotai$1$Chakukaisu$2  int64
ChakuKaisuJyotai$1$Chakukaisu$3  int64
ChakuKaisuJyotai$1$Chakukaisu$4  int64
ChakuKaisuJyotai$1$Chakukaisu$5  int64
ChakuKaisuJyotai$1$Chakukaisu$6  int64
ChakuKaisuJyotai$2$Chakukaisu$1  int64
ChakuKaisuJyotai$2$Chakukaisu$2  int64
ChakuKaisuJyotai$2$Chakukaisu$3  int64
ChakuKaisuJyotai$2$Chakukaisu$4  int64
ChakuKaisuJyotai$2$Chakukaisu$5  int64
ChakuKaisuJyotai$2$Chakukaisu$6  int64
ChakuKaisuJyotai$3$Chakukaisu$1  int64
ChakuKaisuJyotai$3$Chakukaisu$2  int64
ChakuKaisuJyotai$3$Chakukaisu$3  int64
ChakuKaisuJyotai$3$Chakukaisu$4  int64
ChakuKaisuJyotai$3$Chakukaisu$5  int64
ChakuKaisuJyotai$3$Chakukaisu$6  int64
ChakuKaisuJyotai$4$Chakukaisu$1  int64
ChakuKaisuJyotai$4$Chakukaisu$2  int64
ChakuKaisuJyotai$4$Chakukaisu$3  int64
ChakuKaisuJyotai$4$Chakukaisu$4  int64
ChakuKaisuJyotai$4$Chakukaisu$5  int64
ChakuKaisuJyotai$4$Chakukaisu$6  int64
ChakuKaisuJyotai$5$Chakukaisu$1  int64
ChakuKaisuJyotai$5$Chakukaisu$2  int64
ChakuKaisuJyotai$5$Chakukaisu$3  int64
ChakuKaisuJyotai$5$Chakukaisu$4  int64
ChakuKaisuJyotai$5$Chakukaisu$5  int64
ChakuKaisuJyotai$5$Chakukaisu$6  int64
ChakuKaisuJyotai$6$Chakukaisu$1  int64
ChakuKaisuJyotai$6$Chakukaisu$2  int64
ChakuKaisuJyotai$6$Chakukaisu$3  int64
ChakuKaisuJyotai$6$Chakukaisu$4  int64
ChakuKaisuJyotai$6$Chakukaisu$5  int64
ChakuKaisuJyotai$6$Chakukaisu$6  int64
ChakuKaisuJyotai$7$Chakukaisu$1  int64
ChakuKaisuJyotai$7$Chakukaisu$2  int64
ChakuKaisuJyotai$7$Chakukaisu$3  int64
ChakuKaisuJyotai$7$Chakukaisu$4  int64
ChakuKaisuJyotai$7$Chakukaisu$5  int64
ChakuKaisuJyotai$7$Chakukaisu$6  int64
ChakuKaisuJyotai$8$Chakukaisu$1  int64
ChakuKaisuJyotai$8$Chakukaisu$2  int64
ChakuKaisuJyotai$8$Chakukaisu$3  int64
ChakuKaisuJyotai$8$Chakukaisu$4  int64
ChakuKaisuJyotai$8$Chakukaisu$5  int64
ChakuKaisuJyotai$8$Chakukaisu$6  int64
ChakuKaisuJyotai$9$Chakukaisu$1  int64
ChakuKaisuJyotai$9$Chakukaisu$2  int64
ChakuKaisuJyotai$9$Chakukaisu$3  int64
ChakuKaisuJyotai$9$Chakukaisu$4  int64
ChakuKaisuJyotai$9$Chakukaisu$5  int64
ChakuKaisuJyotai$9$Chakukaisu$6  int64
ChakuKaisuJyotai$10$Chakukaisu$1  int64
ChakuKaisuJyotai$10$Chakukaisu$2  int64
ChakuKaisuJyotai$10$Chakukaisu$3  int64
ChakuKaisuJyotai$10$Chakukaisu$4  int64
ChakuKaisuJyotai$10$Chakukaisu$5  int64
ChakuKaisuJyotai$10$Chakukaisu$6  int64
ChakuKaisuJyotai$11$Chakukaisu$1  int64
ChakuKaisuJyotai$11$Chakukaisu$2  int64
ChakuKaisuJyotai$11$Chakukaisu$3  int64
ChakuKaisuJyotai$11$Chakukaisu$4  int64
ChakuKaisuJyotai$11$Chakukaisu$5  int64
ChakuKaisuJyotai$11$Chakukaisu$6  int64
ChakuKaisuJyotai$12$Chakukaisu$1  int64
ChakuKaisuJyotai$12$Chakukaisu$2  int64
ChakuKaisuJyotai$12$Chakukaisu$3  int64
ChakuKaisuJyotai$12$Chakukaisu$4  int64
ChakuKaisuJyotai$12$Chakukaisu$5  int64
ChakuKaisuJyotai$12$Chakukaisu$6  int64
ChakuKaisuKyori$1$Chakukaisu$1  int64
ChakuKaisuKyori$1$Chakukaisu$2  int64
ChakuKaisuKyori$1$Chakukaisu$3  int64
ChakuKaisuKyori$1$Chakukaisu$4  int64
ChakuKaisuKyori$1$Chakukaisu$5  int64
ChakuKaisuKyori$1$Chakukaisu$6  int64
ChakuKaisuKyori$2$Chakukaisu$1  int64
ChakuKaisuKyori$2$Chakukaisu$2  int64
ChakuKaisuKyori$2$Chakukaisu$3  int64
ChakuKaisuKyori$2$Chakukaisu$4  int64
ChakuKaisuKyori$2$Chakukaisu$5  int64
ChakuKaisuKyori$2$Chakukaisu$6  int64
ChakuKaisuKyori$3$Chakukaisu$1  int64
ChakuKaisuKyori$3$Chakukaisu$2  int64
ChakuKaisuKyori$3$Chakukaisu$3  int64
ChakuKaisuKyori$3$Chakukaisu$4  int64
ChakuKaisuKyori$3$Chakukaisu$5  int64
ChakuKaisuKyori$3$Chakukaisu$6  int64
ChakuKaisuKyori$4$Chakukaisu$1  int64
ChakuKaisuKyori$4$Chakukaisu$2  int64
ChakuKaisuKyori$4$Chakukaisu$3  int64
ChakuKaisuKyori$4$Chakukaisu$4  int64
ChakuKaisuKyori$4$Chakukaisu$5  int64
ChakuKaisuKyori$4$Chakukaisu$6  int64
ChakuKaisuKyori$5$Chakukaisu$1  int64
ChakuKaisuKyori$5$Chakukaisu$2  int64
ChakuKaisuKyori$5$Chakukaisu$3  int64
ChakuKaisuKyori$5$Chakukaisu$4  int64
ChakuKaisuKyori$5$Chakukaisu$5  int64
ChakuKaisuKyori$5$Chakukaisu$6  int64
ChakuKaisuKyori$6$Chakukaisu$1  int64
ChakuKaisuKyori$6$Chakukaisu$2  int64
ChakuKaisuKyori$6$Chakukaisu$3  int64
ChakuKaisuKyori$6$Chakukaisu$4  int64
ChakuKaisuKyori$6$Chakukaisu$5  int64
ChakuKaisuKyori$6$Chakukaisu$6  int64
Kyakusitu$1                int64
Kyakusitu$2                int64
Kyakusitu$3                int64
Kyakusitu$4                int64
RaceCount                  int64
crlf                       object

- Kiểm tra khóa chính KettoNum

In [7]:
UM_df['KettoNum'].describe()

count    1.788420e+05
mean     1.998286e+09
std      1.116631e+07
min      1.936100e+09
25%      1.989104e+09
50%      1.999102e+09
75%      2.008103e+09
max      2.016110e+09
Name: KettoNum, dtype: float64

In [8]:
# Check key KettoNum
len(UM_df['KettoNum'].unique())

171711

- <span style="color:blue">Nhận xét:
    - Có rất nhiều con ngựa bị trùng lặp mã số do update thông tin nhưng chưa xóa, để đơn giản ta chỉ giữ lại một dòng

In [9]:
UM_df.drop_duplicates(subset=['KettoNum'], keep='first', inplace=True)
UM_df

,filename,line_no,head$RecordSpec,head$DataKubun,head$MakeDate$Year,head$MakeDate$Month,head$MakeDate$Day,KettoNum,DelKubun,RegDate$Year,...,ChakuKaisuKyori$6$Chakukaisu$3,ChakuKaisuKyori$6$Chakukaisu$4,ChakuKaisuKyori$6$Chakukaisu$5,ChakuKaisuKyori$6$Chakukaisu$6,Kyakusitu$1,Kyakusitu$2,Kyakusitu$3,Kyakusitu$4,RaceCount,crlf
0,UMXM2018049920180430153312.json,1,UM,4,2014,12,22,2009102487,1,2011,...,0,0,0,0,0,4,2,1,11,\r\n
1,UMXM2018049920180430153312.json,2,UM,4,2017,2,6,2009102488,1,2012,...,0,0,0,0,0,1,1,1,15,\r\n
2,UMXM2018049920180430153312.json,3,UM,4,2013,5,28,2009102489,1,2011,...,0,0,0,0,0,0,1,2,8,\r\n
3,UMXM2018049920180430153312.json,4,UM,9,2012,3,29,2009102490,1,2012,...,0,0,0,0,0,1,1,0,2,\r\n
4,UMXM2018049920180430153312.json,5,UM,4,2016,12,5,2009102491,1,2011,...,0,0,1,0,2,4,6,6,25,\r\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178834,UMFW2018050720180507133121.json,1571,UM,1,2018,5,7,2016106189,0,2018,...,0,0,0,0,0,0,0,0,0,\r\n
178835,UMFW2018050720180507133121.json,1572,UM,1,2018,5,7,2016106227,0,2018,...,0,0,0,0,0,0,0,0,0,\r\n
178839,UMFW2018050720180507133121.json,1576,UM,1,2018,5,7,2016109023,0,2018,...,0,0,0,0,0,0,0,0,0,\r\n
178840,UMFW2018050720180507133121.json,1577,UM,1,2018,5,7,2016110041,0,2018,...,0,0,0,0,0,0,0,0,0,\r\n
178841,UMFW2018050720180507133121.json,1578,UM,1,2018,5,7,2016110091,0,2018,...,0,0,0,0,0,0,0,0,0,\r\n

In [10]:
# Select Columns
UM_selected_columns =  [
                        'KettoNum',
                        'Bamei',
                        'ZaikyuFlag',
                        'SexCD',
                        'HinsyuCD',
                        'KeiroCD',
                        'Ketto3Info$1$HansyokuNum',
                        'Ketto3Info$1$Bamei',
                        'TozaiCD',
                        'ChokyosiCode',
                        'BreederCode',  #
                        'BanusiCode',
                        'RuikeiHonsyoHeiti',
                        'RuikeiHonsyoSyogai',
                        'RuikeiFukaHeichi',
                        'RuikeiFukaSyogai',
                        'RuikeiSyutokuHeichi',
                        'RuikeiSyutokuSyogai',
                        ]
UM_process_df = UM_df[UM_selected_columns]
UM_process_df

,KettoNum,Bamei,ZaikyuFlag,SexCD,HinsyuCD,KeiroCD,Ketto3Info$1$HansyokuNum,Ketto3Info$1$Bamei,TozaiCD,ChokyosiCode,BreederCode,BanusiCode,RuikeiHonsyoHeiti,RuikeiHonsyoSyogai,RuikeiFukaHeichi,RuikeiFukaSyogai,RuikeiSyutokuHeichi,RuikeiSyutokuSyogai
0,2009102487,ピエモンテ,0,2,1,1,11201542,フジキセキ,1,1079,913124,338007,28000,0,0,0,0,0
1,2009102488,セレブリティトーク,0,2,1,4,11201164,ブライアンズタイム,2,1075,913124,362800,0,0,0,0,0,0
2,2009102489,ブーフーウー,0,1,1,3,11202008,スターリングローズ,1,1134,913124,970006,0,0,0,0,3000,0
3,2009102490,シーキングザローズ,0,2,1,4,11202135,シーキングザダイヤ,1,1064,913124,15008,0,0,0,0,0,0
4,2009102491,ミッキーバルーン,0,1,1,1,11202006,キングカメハメハ,2,1123,913124,441007,93200,0,0,0,20000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178834,2016106189,ウサギノワルツ,1,1,1,1,11202272,フリオーソ,1,428,803469,129005,0,0,0,0,0,0
178835,2016106227,アレーテス,1,2,1,4,11202132,メイショウボーラー,2,1104,33305,616800,0,0,0,0,0,0
178839,2016109023,サムシングジャスト,1,2,1,4,11202246,ヴィクトワールピサ,2,1011,600197,148800,0,0,0,0,0,0
178840,2016110041,ショウナンアリアナ,1,2,1,3,11406549,Frankel,2,1117,300733,331002,0,0,0,0,0,0
178841,2016110091,フォートワズワース,1,1,1,4,11406902,Verrazano,2,1148,510706,506800,0,0,0,0,0,0

In [11]:
UM_process_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 171711 entries, 0 to 178841
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   KettoNum                  171711 non-null  int64
 1   Bamei                     171711 non-null  object
 2   ZaikyuFlag                171711 non-null  int64
 3   SexCD                     171711 non-null  int64
 4   HinsyuCD                  171711 non-null  int64
 5   KeiroCD                   171711 non-null  int64
 6   Ketto3Info$1$HansyokuNum  171711 non-null  int64
 7   Ketto3Info$1$Bamei        171711 non-null  object
 8   TozaiCD                   171711 non-null  int64
 9   ChokyosiCode              171711 non-null  int64
 10  BreederCode               171711 non-null  int64
 11  BanusiCode                171711 non-null  int64
 12  RuikeiHonsyoHeiti         171711 non-null  int64
 13  RuikeiHonsyoSyogai        171711 non-null  int64
 14  RuikeiFukaHeichi          171711 non-null  int64
 15  RuikeiFukaSyogai          171711 non-null  int64
 16  RuikeiSyutokuHeichi       171711 non-null  int64
 17  RuikeiSyutokuSyogai       171711 non-null  int64
dtypes: int64(16), object(2)
memory usage: 29.9+ MB

In [7]:
# Đổi tên các cột TozaiCD thành UM_TozaiCD
for column in UM_selected_columns:
    if column != 'KettoNum':
        new_column = 'UM_' + column
        UM_process_df[new_column] = UM_process_df[column]
        UM_process_df.drop(column, axis=1, inplace=True)
UM_process_df

<ipython-input-7-f5d4510cc79c>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  UM_process_df[new_column] = UM_process_df[column]
C:\ProgramData\Anaconda3\envs\my_d2l\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,KettoNum,UM_Bamei,UM_ZaikyuFlag,UM_SexCD,UM_HinsyuCD,UM_KeiroCD,UM_Ketto3Info$1$HansyokuNum,UM_Ketto3Info$1$Bamei,UM_TozaiCD,UM_ChokyosiCode,UM_BreederCode,UM_BanusiCode,UM_RuikeiHonsyoHeiti,UM_RuikeiHonsyoSyogai,UM_RuikeiFukaHeichi,UM_RuikeiFukaSyogai,UM_RuikeiSyutokuHeichi,UM_RuikeiSyutokuSyogai
0,2009102487,ピエモンテ,0,2,1,1,11201542,フジキセキ,1,1079,913124,338007,28000,0,0,0,0,0
1,2009102488,セレブリティトーク,0,2,1,4,11201164,ブライアンズタイム,2,1075,913124,362800,0,0,0,0,0,0
2,2009102489,ブーフーウー,0,1,1,3,11202008,スターリングローズ,1,1134,913124,970006,0,0,0,0,3000,0
3,2009102490,シーキングザローズ,0,2,1,4,11202135,シーキングザダイヤ,1,1064,913124,15008,0,0,0,0,0,0
4,2009102491,ミッキーバルーン,0,1,1,1,11202006,キングカメハメハ,2,1123,913124,441007,93200,0,0,0,20000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178834,2016106189,ウサギノワルツ,1,1,1,1,11202272,フリオーソ,1,428,803469,129005,0,0,0,0,0,0
178835,2016106227,アレーテス,1,2,1,4,11202132,メイショウボーラー,2,1104,33305,616800,0,0,0,0,0,0
178839,2016109023,サムシングジャスト,1,2,1,4,11202246,ヴィクトワールピサ,2,1011,600197,148800,0,0,0,0,0,0
178840,2016110041,ショウナンアリアナ,1,2,1,3,11406549,Frankel,2,1117,300733,331002,0,0,0,0,0,0
178841,2016110091,フォートワズワース,1,1,1,4,11406902,Verrazano,2,1148,510706,506800,0,0,0,0,0,0

In [8]:
UM_process_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 171711 entries, 0 to 178841
Data columns (total 18 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   KettoNum                     171711 non-null  int64
 1   UM_Bamei                     171711 non-null  object
 2   UM_ZaikyuFlag                171711 non-null  int64
 3   UM_SexCD                     171711 non-null  int64
 4   UM_HinsyuCD                  171711 non-null  int64
 5   UM_KeiroCD                   171711 non-null  int64
 6   UM_Ketto3Info$1$HansyokuNum  171711 non-null  int64
 7   UM_Ketto3Info$1$Bamei        171711 non-null  object
 8   UM_TozaiCD                   171711 non-null  int64
 9   UM_ChokyosiCode              171711 non-null  int64
 10  UM_BreederCode               171711 non-null  int64
 11  UM_BanusiCode                171711 non-null  int64
 12  UM_RuikeiHonsyoHeiti         171711 non-null  int64
 13  UM_RuikeiHonsyoSyogai        171711 non-null  int64
 14  UM_RuikeiFukaHeichi          171711 non-null  int64
 15  UM_RuikeiFukaSyogai          171711 non-null  int64
 16  UM_RuikeiSyutokuHeichi       171711 non-null  int64
 17  UM_RuikeiSyutokuSyogai       171711 non-null  int64
dtypes: int64(16), object(2)
memory usage: 24.9+ MB

In [9]:
UM_process_df.describe(include='all')

,KettoNum,UM_Bamei,UM_ZaikyuFlag,UM_SexCD,UM_HinsyuCD,UM_KeiroCD,UM_Ketto3Info$1$HansyokuNum,UM_Ketto3Info$1$Bamei,UM_TozaiCD,UM_ChokyosiCode,UM_BreederCode,UM_BanusiCode,UM_RuikeiHonsyoHeiti,UM_RuikeiHonsyoSyogai,UM_RuikeiFukaHeichi,UM_RuikeiFukaSyogai,UM_RuikeiSyutokuHeichi,UM_RuikeiSyutokuSyogai
count,1.717110e+05,171711,171711.000000,171711.000000,171711.000000,171711.000000,1.717110e+05,171711,171711.000000,171711.000000,171711.000000,171711.000000,1.717110e+05,1.717110e+05,1.717110e+05,171711.000000,1.717110e+05,1.717110e+05
unique,NaN,166082,NaN,NaN,NaN,NaN,NaN,3736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,パルティータ,NaN,NaN,NaN,NaN,NaN,フジキセキ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,5,NaN,NaN,NaN,NaN,NaN,1563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.997629e+09,NaN,0.023079,1.509204,1.056618,3.039165,1.167102e+07,NaN,1.503095,609.965250,452923.381758,481960.056461,1.246349e+05,6.564292e+03,1.320942e+03,13.890642,2.745122e+04,1.887980e+03
std,1.090682e+07,NaN,0.150156,0.556678,0.454355,1.531255,4.389122e+06,NaN,0.543587,693.596836,282683.472970,281513.441574,3.540988e+05,7.076593e+04,1.455976e+04,395.074523,1.019549e+05,2.756045e+04
min,1.936100e+09,NaN,0.000000,1.000000,1.000000,1.000000,0.000000e+00,NaN,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
25%,1.989100e+09,NaN,0.000000,1.000000,1.000000,3.000000,1.120072e+07,NaN,1.000000,264.000000,220204.000000,258901.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
50%,1.998104e+09,NaN,0.000000,1.000000,1.000000,3.000000,1.120148e+07,NaN,1.000000,377.000000,401124.000000,476800.000000,1.100000e+04,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
75%,2.007103e+09,NaN,0.000000,2.000000,1.000000,4.000000,1.120192e+07,NaN,2.000000,1026.000000,700380.000000,714002.000000,9.850000e+04,0.000000e+00,0.000000e+00,0.000000,2.000000e+04,0.000000e+00
max,2.016110e+09,NaN,1.000000,3.000000,6.000000,11.000000,7.110099e+07,NaN,4.000000,5718.000000,993201.000000,999800.000000,1.813200e+07,5.293000e+06,1.318160e+06,53000.000000,7.062500e+06,3.186960e+06

In [10]:
# Ghi file
UM_process_df.to_csv('UM_process_df.csv', index=False)

In [11]:
# Đọc File
UM_process_df = pd.read_csv('UM_process_df.csv')
UM_process_df

,KettoNum,UM_Bamei,UM_ZaikyuFlag,UM_SexCD,UM_HinsyuCD,UM_KeiroCD,UM_Ketto3Info$1$HansyokuNum,UM_Ketto3Info$1$Bamei,UM_TozaiCD,UM_ChokyosiCode,UM_BreederCode,UM_BanusiCode,UM_RuikeiHonsyoHeiti,UM_RuikeiHonsyoSyogai,UM_RuikeiFukaHeichi,UM_RuikeiFukaSyogai,UM_RuikeiSyutokuHeichi,UM_RuikeiSyutokuSyogai
0,2009102487,ピエモンテ,0,2,1,1,11201542,フジキセキ,1,1079,913124,338007,28000,0,0,0,0,0
1,2009102488,セレブリティトーク,0,2,1,4,11201164,ブライアンズタイム,2,1075,913124,362800,0,0,0,0,0,0
2,2009102489,ブーフーウー,0,1,1,3,11202008,スターリングローズ,1,1134,913124,970006,0,0,0,0,3000,0
3,2009102490,シーキングザローズ,0,2,1,4,11202135,シーキングザダイヤ,1,1064,913124,15008,0,0,0,0,0,0
4,2009102491,ミッキーバルーン,0,1,1,1,11202006,キングカメハメハ,2,1123,913124,441007,93200,0,0,0,20000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171706,2016106189,ウサギノワルツ,1,1,1,1,11202272,フリオーソ,1,428,803469,129005,0,0,0,0,0,0
171707,2016106227,アレーテス,1,2,1,4,11202132,メイショウボーラー,2,1104,33305,616800,0,0,0,0,0,0
171708,2016109023,サムシングジャスト,1,2,1,4,11202246,ヴィクトワールピサ,2,1011,600197,148800,0,0,0,0,0,0
171709,2016110041,ショウナンアリアナ,1,2,1,3,11406549,Frankel,2,1117,300733,331002,0,0,0,0,0,0
171710,2016110091,フォートワズワース,1,1,1,4,11406902,Verrazano,2,1148,510706,506800,0,0,0,0,0,0

In [12]:
UM_process_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171711 entries, 0 to 171710
Data columns (total 18 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   KettoNum                     171711 non-null  int64
 1   UM_Bamei                     171711 non-null  object
 2   UM_ZaikyuFlag                171711 non-null  int64
 3   UM_SexCD                     171711 non-null  int64
 4   UM_HinsyuCD                  171711 non-null  int64
 5   UM_KeiroCD                   171711 non-null  int64
 6   UM_Ketto3Info$1$HansyokuNum  171711 non-null  int64
 7   UM_Ketto3Info$1$Bamei        171711 non-null  object
 8   UM_TozaiCD                   171711 non-null  int64
 9   UM_ChokyosiCode              171711 non-null  int64
 10  UM_BreederCode               171711 non-null  int64
 11  UM_BanusiCode                171711 non-null  int64
 12  UM_RuikeiHonsyoHeiti         171711 non-null  int64
 13  UM_RuikeiHonsyoSyogai        171711 non-null  int64
 14  UM_RuikeiFukaHeichi          171711 non-null  int64
 15  UM_RuikeiFukaSyogai          171711 non-null  int64
 16  UM_RuikeiSyutokuHeichi       171711 non-null  int64
 17  UM_RuikeiSyutokuSyogai       171711 non-null  int64
dtypes: int64(16), object(2)
memory usage: 23.6+ MB